[base]
package = ocean
env_name = showdown
policy_name = Showdown
rnn_name = ShowdownLSTM
max_suggestion_cost = 3600

[vec]
backend = Multiprocessing
num_envs = 4
num_workers = auto
batch_size = auto
zero_copy = True
seed = 42

[env]
num_envs = 1024
num_agents = 1
[policy]
hidden_size = 512
[rnn]
input_size = 512
hidden_size = 512

[train]
name = pufferai 
project = ablations
use_rnn = True
seed = 42
torch_deterministic = True
cpu_offload = False
device = cuda
optimizer = muon
anneal_lr = True
precision = float32
total_timesteps = 5e07
learning_rate =  0.01916835137200499
gamma = 0.9952075034043409
gae_lambda = 0.5999999999999999
update_epochs = 1
clip_coef = 0.16960424076316113
vf_coef = 0.81259864433164
vf_clip_coef = 1.307047327793967
max_grad_norm = 1.8621512406663059
ent_coef = 0.0021683299623659158
adam_beta1 = 0.7269809866778326
adam_beta2 = 0.9999667602950376
adam_eps = 0.7269809866778326

data_dir = experiments
checkpoint_interval = 200
batch_size = auto
minibatch_size = 16384

# Accumulate gradients above this size
max_minibatch_size = 32768
bptt_horizon = 64
compile = False
compile_mode = reduce-overhead
compile_fullgraph = True

vtrace_rho_clip = 2.0817453908623427
vtrace_c_clip = 0.9800667998253537

prio_alpha = 0.7212807074175657
prio_beta0 =  0.9257177079160461

[sweep]
method = Protein 
metric = score
goal = maximize
downsample = 10

# TODO: Elim from base
[sweep.train.total_timesteps]
distribution = log_normal
min = 5e7
max = 1e9
mean = 1e8
scale = time

[sweep.train.bptt_horizon]
distribution = uniform_pow2
min = 16
max = 64
mean = 64
scale = auto

[sweep.train.minibatch_size]
distribution = uniform_pow2
min = 8192
max = 65536
mean = 32768
scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.00001
mean = 0.01
max = 0.1
scale = 0.5

[sweep.train.ent_coef]
distribution = log_normal
min = 0.00001
mean = 0.01
max = 0.2
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.8
mean = 0.98
max = 0.9999
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.6
mean = 0.95
max = 0.995
scale = auto

[sweep.train.vtrace_rho_clip]
distribution = uniform
min = 0.0
max = 5.0
mean = 1.0
scale = auto

[sweep.train.vtrace_c_clip]
distribution = uniform
min = 0.0
max = 5.0
mean = 1.0
scale = auto

#[sweep.train.update_epochs]
#distribution = int_uniform
#min = 1
#max = 8
#mean = 1
#scale = 2.0

[sweep.train.clip_coef]
distribution = uniform
min = 0.01
max = 1.0
mean = 0.2
scale = auto

# Optimal vf clip can be lower than 0.1,
# but this results in jank unstable runs
[sweep.train.vf_clip_coef]
distribution = uniform
min = 0.1
max = 5.0
mean = 0.2
scale = auto

[sweep.train.vf_coef]
distribution = uniform
min = 0.0
max = 5.0
mean = 2.0
scale = auto

[sweep.train.max_grad_norm]
distribution = uniform
min = 0.0
mean = 1.0
max = 5.0
scale = auto

[sweep.train.adam_beta1]
distribution = logit_normal
min = 0.5
mean = 0.9
max = 0.999
scale = auto

[sweep.train.adam_beta2]
distribution = logit_normal
min = 0.9
mean = 0.999
max = 0.99999
scale = auto

[sweep.train.adam_eps]
distribution = log_normal
min = 1e-14
mean = 1e-8
max = 1e-4
scale = auto

[sweep.train.prio_alpha]
distribution = logit_normal
min = 0.1
mean = 0.85
max = 0.99
scale = auto

[sweep.train.prio_beta0]
distribution = logit_normal
min = 0.1
mean = 0.85
max = 0.99
scale = auto
